Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/02/2021
Var
// Seção de Declarações das variáveis 
delta <- Exp(b, 2.0) - 4 *a*c

x1 <- (-b + RaizQ(delta) )/ (2.0 * a)

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo